import type { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about',
          '/accessibility',
          '/affiliate',
          '/ca-privacy',
          '/cart',
          '/collections',
          '/collections/*',
          '/contact',
          '/faq',
          '/gift-cards',
          '/influencers',
          '/jobs',
          '/press',
          '/privacy',
          '/products/*',
          '/returns',
          '/shipping',
          '/size-guide',
          '/sustainability',
          '/terms',
          '/track',
        ],
        disallow: [
          '/admin',
          '/admin/*',
          '/account',
          '/account/*',
          '/checkout',
          '/checkout/*',
          '/api/*',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/collections',
          '/collections/*',
          '/products/*',
          '/about',
          '/contact',
          '/shipping',
          '/returns',
          '/faq',
          '/size-guide',
          '/privacy',
          '/terms',
          '/sustainability',
          '/press',
          '/jobs',
          '/affiliate',
          '/gift-cards',
          '/influencers',
          '/ca-privacy',
          '/accessibility',
          '/track',
        ],
        disallow: [
          '/admin',
          '/admin/*',
          '/account',
          '/account/*',
          '/checkout',
          '/checkout/*',
          '/api/*',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/collections',
          '/collections/*',
          '/products/*',
          '/about',
          '/contact',
        ],
        disallow: [
          '/admin',
          '/admin/*',
          '/account',
          '/account/*',
          '/checkout',
          '/checkout/*',
          '/api/*',
        ],
      },
    ],
    sitemap: 'https://solomonandsage.com/sitemap.xml',
  }
}
